problemesData = [
  {
    title: "Contains Duplicate",
    link: "https://leetcode.com/problems/contains-duplicate/",
    pattern: "Arrays & Hashing",
    difficulty: "Easy",
  },
  {
    title: "Valid Anagram",
    link: "https://leetcode.com/problems/valid-anagram/",
    pattern: "Arrays & Hashing",
    difficulty: "Easy",
  },
  {
    title: "Two Sum",
    link: "https://leetcode.com/problems/two-sum/",
    pattern: "Arrays & Hashing",
    difficulty: "Easy",
  },
  {
    title: "Group Anagrams",
    link: "https://leetcode.com/problems/group-anagrams/",
    pattern: "Arrays & Hashing",
    difficulty: "Medium",
  },
  {
    title: "Top K Frequent Elements",
    link: "https://leetcode.com/problems/top-k-frequent-elements/",
    pattern: "Arrays & Hashing",
    difficulty: "Medium",
  },
  {
    title: "Product Of Array Except Self",
    link: "https://leetcode.com/problems/product-of-array-except-self/",
    pattern: "Arrays & Hashing",
    difficulty: "Medium",
  },
  {
    title: "Valid Sudoku",
    link: "https://leetcode.com/problems/valid-sudoku/",
    pattern: "Arrays & Hashing",
    difficulty: "Medium",
  },
  {
    title: "Encode And Decode Strings",
    link: "https://leetcode.com/problems/encode-and-decode-strings/",
    pattern: "Arrays & Hashing",
    difficulty: "Medium",
  },
  {
    title: "Longest Consecutive Sequence",
    link: "https://leetcode.com/problems/longest-consecutive-sequence/",
    pattern: "Arrays & Hashing",
    difficulty: "Medium",
  },
  {
    title: "Valid Palindrome",
    link: "https://leetcode.com/problems/valid-palindrome/",
    pattern: "Two Pointers",
    difficulty: "Easy",
  },
  {
    title: "Two Sum II Input Array Is Sorted",
    link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
    pattern: "Two Pointers",
    difficulty: "Medium",
  },
  {
    title: "3sum",
    link: "https://leetcode.com/problems/3sum/",
    pattern: "Two Pointers",
    difficulty: "Medium",
  },
  {
    title: "Container With Most Water",
    link: "https://leetcode.com/problems/container-with-most-water/",
    pattern: "Two Pointers",
    difficulty: "Medium",
  },
  {
    title: "Trapping Rain Water",
    link: "https://leetcode.com/problems/trapping-rain-water/",
    pattern: "Two Pointers",
    difficulty: "Hard",
  },
  {
    title: "Best Time To Buy And Sell Stock",
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    pattern: "Sliding Window",
    difficulty: "Easy",
  },
  {
    title: "Longest Substring Without Repeating Characters",
    link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    pattern: "Sliding Window",
    difficulty: "Medium",
  },
  {
    title: "Longest Repeating Character Replacement",
    link: "https://leetcode.com/problems/longest-repeating-character-replacement/",
    pattern: "Sliding Window",
    difficulty: "Medium",
  },
  {
    title: "Permutation In String",
    link: "https://leetcode.com/problems/permutation-in-string/",
    pattern: "Sliding Window",
    difficulty: "Medium",
  },
  {
    title: "Minimum Window Substring",
    link: "https://leetcode.com/problems/minimum-window-substring/",
    pattern: "Sliding Window",
    difficulty: "Hard",
  },
  {
    title: "Sliding Window Maximum",
    link: "https://leetcode.com/problems/sliding-window-maximum/",
    pattern: "Sliding Window",
    difficulty: "Hard",
  },
  {
    title: "Valid Parentheses",
    link: "https://leetcode.com/problems/valid-parentheses/",
    pattern: "Stack",
    difficulty: "Easy",
  },
  {
    title: "Min Stack",
    link: "https://leetcode.com/problems/min-stack/",
    pattern: "Stack",
    difficulty: "Medium",
  },
  {
    title: "Evaluate Reverse Polish Notation",
    link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    pattern: "Stack",
    difficulty: "Medium",
  },
  {
    title: "Generate Parentheses",
    link: "https://leetcode.com/problems/generate-parentheses/",
    pattern: "Stack",
    difficulty: "Medium",
  },
  {
    title: "Daily Temperatures",
    link: "https://leetcode.com/problems/daily-temperatures/",
    pattern: "Stack",
    difficulty: "Medium",
  },
  {
    title: "Car Fleet",
    link: "https://leetcode.com/problems/car-fleet/",
    pattern: "Stack",
    difficulty: "Medium",
  },
  {
    title: "Largest Rectangle In Histogram",
    link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    pattern: "Stack",
    difficulty: "Hard",
  },
  {
    title: "Binary Search",
    link: "https://leetcode.com/problems/binary-search/",
    pattern: "Binary Search",
    difficulty: "Easy",
  },
  {
    title: "Search A 2d Matrix",
    link: "https://leetcode.com/problems/search-a-2d-matrix/",
    pattern: "Binary Search",
    difficulty: "Medium",
  },
  {
    title: "Koko Eating Bananas",
    link: "https://leetcode.com/problems/koko-eating-bananas/",
    pattern: "Binary Search",
    difficulty: "Medium",
  },
  {
    title: "Search In Rotated Sorted Array",
    link: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    pattern: "Binary Search",
    difficulty: "Medium",
  },
  {
    title: "Find Minimum In Rotated Sorted Array",
    link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    pattern: "Binary Search",
    difficulty: "Medium",
  },
  {
    title: "Time Based Key Value Store",
    link: "https://leetcode.com/problems/time-based-key-value-store/",
    pattern: "Binary Search",
    difficulty: "Medium",
  },
  {
    title: "Median Of Two Sorted Arrays",
    link: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    pattern: "Binary Search",
    difficulty: "Hard",
  },
  {
    title: "Reverse Linked List",
    link: "https://leetcode.com/problems/reverse-linked-list/",
    pattern: "Linked List",
    difficulty: "Easy",
  },
  {
    title: "Merge Two Sorted Lists",
    link: "https://leetcode.com/problems/merge-two-sorted-lists/",
    pattern: "Linked List",
    difficulty: "Easy",
  },
  {
    title: "Reorder List",
    link: "https://leetcode.com/problems/reorder-list/",
    pattern: "Linked List",
    difficulty: "Medium",
  },
  {
    title: "Remove Nth Node From End Of List",
    link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    pattern: "Linked List",
    difficulty: "Medium",
  },
  {
    title: "Copy List With Random Pointer",
    link: "https://leetcode.com/problems/copy-list-with-random-pointer/",
    pattern: "Linked List",
    difficulty: "Medium",
  },
  {
    title: "Add Two Numbers",
    link: "https://leetcode.com/problems/add-two-numbers/",
    pattern: "Linked List",
    difficulty: "Medium",
  },
  {
    title: "Linked List Cycle",
    link: "https://leetcode.com/problems/linked-list-cycle/",
    pattern: "Linked List",
    difficulty: "Easy",
  },
  {
    title: "Find The Duplicate Number",
    link: "https://leetcode.com/problems/find-the-duplicate-number/",
    pattern: "Linked List",
    difficulty: "Medium",
  },
  {
    title: "Lru Cache",
    link: "https://leetcode.com/problems/lru-cache/",
    pattern: "Linked List",
    difficulty: "Medium",
  },
  {
    title: "Merge K Sorted Lists",
    link: "https://leetcode.com/problems/merge-k-sorted-lists/",
    pattern: "Linked List",
    difficulty: "Hard",
  },
  {
    title: "Reverse Nodes In K Group",
    link: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    pattern: "Linked List",
    difficulty: "Hard",
  },
  {
    title: "Invert Binary Tree",
    link: "https://leetcode.com/problems/invert-binary-tree/",
    pattern: "Trees",
    difficulty: "Easy",
  },
  {
    title: "Maximum Depth Of Binary Tree",
    link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    pattern: "Trees",
    difficulty: "Easy",
  },
  {
    title: "Diameter Of Binary Tree",
    link: "https://leetcode.com/problems/diameter-of-binary-tree/",
    pattern: "Trees",
    difficulty: "Easy",
  },
  {
    title: "Balanced Binary Tree",
    link: "https://leetcode.com/problems/balanced-binary-tree/",
    pattern: "Trees",
    difficulty: "Easy",
  },
  {
    title: "Same Tree",
    link: "https://leetcode.com/problems/same-tree/",
    pattern: "Trees",
    difficulty: "Easy",
  },
  {
    title: "Subtree Of Another Tree",
    link: "https://leetcode.com/problems/subtree-of-another-tree/",
    pattern: "Trees",
    difficulty: "Easy",
  },
  {
    title: "Lowest Common Ancestor Of A Binary Search Tree",
    link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    pattern: "Trees",
    difficulty: "Easy",
  },
  {
    title: "Binary Tree Level Order Traversal",
    link: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    pattern: "Trees",
    difficulty: "Medium",
  },
  {
    title: "Binary Tree Right Side View",
    link: "https://leetcode.com/problems/binary-tree-right-side-view/",
    pattern: "Trees",
    difficulty: "Medium",
  },
  {
    title: "Count Good Nodes In Binary Tree",
    link: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
    pattern: "Trees",
    difficulty: "Medium",
  },
  {
    title: "Validate Binary Search Tree",
    link: "https://leetcode.com/problems/validate-binary-search-tree/",
    pattern: "Trees",
    difficulty: "Medium",
  },
  {
    title: "Kth Smallest Element In A Bst",
    link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    pattern: "Trees",
    difficulty: "Medium",
  },
  {
    title: "Construct Binary Tree From Preorder And Inorder Traversal",
    link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
    pattern: "Trees",
    difficulty: "Medium",
  },
  {
    title: "Binary Tree Maximum Path Sum",
    link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    pattern: "Trees",
    difficulty: "Hard",
  },
  {
    title: "Serialize And Deserialize Binary Tree",
    link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    pattern: "Trees",
    difficulty: "Hard",
  },
  {
    title: "Implement Trie Prefix Tree",
    link: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    pattern: "Tries",
    difficulty: "Medium",
  },
  {
    title: "Design Add And Search Words Data Structure",
    link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
    pattern: "Tries",
    difficulty: "Medium",
  },
  {
    title: "Word Search II",
    link: "https://leetcode.com/problems/word-search-ii/",
    pattern: "Tries",
    difficulty: "Hard",
  },
  {
    title: "Kth Largest Element In A Stream",
    link: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
    pattern: "Heap / Priority Queue",
    difficulty: "Easy",
  },
  {
    title: "Last Stone Weight",
    link: "https://leetcode.com/problems/last-stone-weight/",
    pattern: "Heap / Priority Queue",
    difficulty: "Easy",
  },
  {
    title: "K Closest Points To Origin",
    link: "https://leetcode.com/problems/k-closest-points-to-origin/",
    pattern: "Heap / Priority Queue",
    difficulty: "Medium",
  },
  {
    title: "Kth Largest Element In An Array",
    link: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    pattern: "Heap / Priority Queue",
    difficulty: "Medium",
  },
  {
    title: "Task Scheduler",
    link: "https://leetcode.com/problems/task-scheduler/",
    pattern: "Heap / Priority Queue",
    difficulty: "Medium",
  },
  {
    title: "Design Twitter",
    link: "https://leetcode.com/problems/design-twitter/",
    pattern: "Heap / Priority Queue",
    difficulty: "Medium",
  },
  {
    title: "Find Median From Data Stream",
    link: "https://leetcode.com/problems/find-median-from-data-stream/",
    pattern: "Heap / Priority Queue",
    difficulty: "Hard",
  },
  {
    title: "Subsets",
    link: "https://leetcode.com/problems/subsets/",
    pattern: "Backtracking",
    difficulty: "Medium",
  },
  {
    title: "Combination Sum",
    link: "https://leetcode.com/problems/combination-sum/",
    pattern: "Backtracking",
    difficulty: "Medium",
  },
  {
    title: "Permutations",
    link: "https://leetcode.com/problems/permutations/",
    pattern: "Backtracking",
    difficulty: "Medium",
  },
  {
    title: "Subsets II",
    link: "https://leetcode.com/problems/subsets-ii/",
    pattern: "Backtracking",
    difficulty: "Medium",
  },
  {
    title: "Combination Sum II",
    link: "https://leetcode.com/problems/combination-sum-ii/",
    pattern: "Backtracking",
    difficulty: "Medium",
  },
  {
    title: "Word Search",
    link: "https://leetcode.com/problems/word-search/",
    pattern: "Backtracking",
    difficulty: "Medium",
  },
  {
    title: "Palindrome Partitioning",
    link: "https://leetcode.com/problems/palindrome-partitioning/",
    pattern: "Backtracking",
    difficulty: "Medium",
  },
  {
    title: "Letter Combinations Of A Phone Number",
    link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    pattern: "Backtracking",
    difficulty: "Medium",
  },
  {
    title: "N Queens",
    link: "https://leetcode.com/problems/n-queens/",
    pattern: "Backtracking",
    difficulty: "Hard",
  },
  {
    title: "Number Of Islands",
    link: "https://leetcode.com/problems/number-of-islands/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Clone Graph",
    link: "https://leetcode.com/problems/clone-graph/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Max Area Of Island",
    link: "https://leetcode.com/problems/max-area-of-island/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Pacific Atlantic Water Flow",
    link: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Surrounded Regions",
    link: "https://leetcode.com/problems/surrounded-regions/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Rotting Oranges",
    link: "https://leetcode.com/problems/rotting-oranges/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Walls And Gates",
    link: "https://leetcode.com/problems/walls-and-gates/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Course Schedule",
    link: "https://leetcode.com/problems/course-schedule/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Course Schedule II",
    link: "https://leetcode.com/problems/course-schedule-ii/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Redundant Connection",
    link: "https://leetcode.com/problems/redundant-connection/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Number Of Connected Components In An Undirected Graph",
    link: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Graph Valid Tree",
    link: "https://leetcode.com/problems/graph-valid-tree/",
    pattern: "Graphs",
    difficulty: "Medium",
  },
  {
    title: "Word Ladder",
    link: "https://leetcode.com/problems/word-ladder/",
    pattern: "Graphs",
    difficulty: "Hard",
  },
  {
    title: "Reconstruct Itinerary",
    link: "https://leetcode.com/problems/reconstruct-itinerary/",
    pattern: "Advanced Graphs",
    difficulty: "Hard",
  },
  {
    title: "Min Cost To Connect All Points",
    link: "https://leetcode.com/problems/min-cost-to-connect-all-points/",
    pattern: "Advanced Graphs",
    difficulty: "Medium",
  },
  {
    title: "Network Delay Time",
    link: "https://leetcode.com/problems/network-delay-time/",
    pattern: "Advanced Graphs",
    difficulty: "Medium",
  },
  {
    title: "Swim In Rising Water",
    link: "https://leetcode.com/problems/swim-in-rising-water/",
    pattern: "Advanced Graphs",
    difficulty: "Hard",
  },
  {
    title: "Alien Dictionary",
    link: "https://leetcode.com/problems/alien-dictionary/",
    pattern: "Advanced Graphs",
    difficulty: "Hard",
  },
  {
    title: "Cheapest Flights Within K Stops",
    link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
    pattern: "Advanced Graphs",
    difficulty: "Medium",
  },
  {
    title: "Climbing Stairs",
    link: "https://leetcode.com/problems/climbing-stairs/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Easy",
  },
  {
    title: "Min Cost Climbing Stairs",
    link: "https://leetcode.com/problems/min-cost-climbing-stairs/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Easy",
  },
  {
    title: "House Robber",
    link: "https://leetcode.com/problems/house-robber/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "House Robber II",
    link: "https://leetcode.com/problems/house-robber-ii/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Longest Palindromic Substring",
    link: "https://leetcode.com/problems/longest-palindromic-substring/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Palindromic Substrings",
    link: "https://leetcode.com/problems/palindromic-substrings/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Decode Ways",
    link: "https://leetcode.com/problems/decode-ways/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Coin Change",
    link: "https://leetcode.com/problems/coin-change/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Maximum Product Subarray",
    link: "https://leetcode.com/problems/maximum-product-subarray/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Word Break",
    link: "https://leetcode.com/problems/word-break/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Longest Increasing Subsequence",
    link: "https://leetcode.com/problems/longest-increasing-subsequence/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Partition Equal Subset Sum",
    link: "https://leetcode.com/problems/partition-equal-subset-sum/",
    pattern: "1-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Unique Paths",
    link: "https://leetcode.com/problems/unique-paths/",
    pattern: "2-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Longest Common Subsequence",
    link: "https://leetcode.com/problems/longest-common-subsequence/",
    pattern: "2-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Best Time To Buy And Sell Stock With Cooldown",
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
    pattern: "2-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Coin Change 2",
    link: "https://leetcode.com/problems/coin-change-2/",
    pattern: "2-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Target Sum",
    link: "https://leetcode.com/problems/target-sum/",
    pattern: "2-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Interleaving String",
    link: "https://leetcode.com/problems/interleaving-string/",
    pattern: "2-D Dynamic Programming",
    difficulty: "Medium",
  },
  {
    title: "Longest Increasing Path In A Matrix",
    link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
    pattern: "2-D Dynamic Programming",
    difficulty: "Hard",
  },
  {
    title: "Distinct Subsequences",
    link: "https://leetcode.com/problems/distinct-subsequences/",
    pattern: "2-D Dynamic Programming",
    difficulty: "Hard",
  },
  {
    title: "Edit Distance",
    link: "https://leetcode.com/problems/edit-distance/",
    pattern: "2-D Dynamic Programming",
    difficulty: "Hard",
  },
  {
    title: "Burst Balloons",
    link: "https://leetcode.com/problems/burst-balloons/",
    pattern: "2-D Dynamic Programming",
    difficulty: "Hard",
  },
  {
    title: "Regular Expression Matching",
    link: "https://leetcode.com/problems/regular-expression-matching/",
    pattern: "2-D Dynamic Programming",
    difficulty: "Hard",
  },
  {
    title: "Maximum Subarray",
    link: "https://leetcode.com/problems/maximum-subarray/",
    pattern: "Greedy",
    difficulty: "Medium",
  },
  {
    title: "Jump Game",
    link: "https://leetcode.com/problems/jump-game/",
    pattern: "Greedy",
    difficulty: "Medium",
  },
  {
    title: "Jump Game II",
    link: "https://leetcode.com/problems/jump-game-ii/",
    pattern: "Greedy",
    difficulty: "Medium",
  },
  {
    title: "Gas Station",
    link: "https://leetcode.com/problems/gas-station/",
    pattern: "Greedy",
    difficulty: "Medium",
  },
  {
    title: "Hand Of Straights",
    link: "https://leetcode.com/problems/hand-of-straights/",
    pattern: "Greedy",
    difficulty: "Medium",
  },
  {
    title: "Merge Triplets To Form Target Triplet",
    link: "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/",
    pattern: "Greedy",
    difficulty: "Medium",
  },
  {
    title: "Partition Labels",
    link: "https://leetcode.com/problems/partition-labels/",
    pattern: "Greedy",
    difficulty: "Medium",
  },
  {
    title: "Valid Parenthesis String",
    link: "https://leetcode.com/problems/valid-parenthesis-string/",
    pattern: "Greedy",
    difficulty: "Medium",
  },
  {
    title: "Insert Interval",
    link: "https://leetcode.com/problems/insert-interval/",
    pattern: "Intervals",
    difficulty: "Medium",
  },
  {
    title: "Merge Intervals",
    link: "https://leetcode.com/problems/merge-intervals/",
    pattern: "Intervals",
    difficulty: "Medium",
  },
  {
    title: "Non Overlapping Intervals",
    link: "https://leetcode.com/problems/non-overlapping-intervals/",
    pattern: "Intervals",
    difficulty: "Medium",
  },
  {
    title: "Meeting Rooms",
    link: "https://leetcode.com/problems/meeting-rooms/",
    pattern: "Intervals",
    difficulty: "Easy",
  },
  {
    title: "Meeting Rooms II",
    link: "https://leetcode.com/problems/meeting-rooms-ii/",
    pattern: "Intervals",
    difficulty: "Medium",
  },
  {
    title: "Minimum Interval To Include Each Query",
    link: "https://leetcode.com/problems/minimum-interval-to-include-each-query/",
    pattern: "Intervals",
    difficulty: "Hard",
  },
  {
    title: "Rotate Image",
    link: "https://leetcode.com/problems/rotate-image/",
    pattern: "Math & Geometry",
    difficulty: "Medium",
  },
  {
    title: "Spiral Matrix",
    link: "https://leetcode.com/problems/spiral-matrix/",
    pattern: "Math & Geometry",
    difficulty: "Medium",
  },
  {
    title: "Set Matrix Zeroes",
    link: "https://leetcode.com/problems/set-matrix-zeroes/",
    pattern: "Math & Geometry",
    difficulty: "Medium",
  },
  {
    title: "Happy Number",
    link: "https://leetcode.com/problems/happy-number/",
    pattern: "Math & Geometry",
    difficulty: "Easy",
  },
  {
    title: "Plus One",
    link: "https://leetcode.com/problems/plus-one/",
    pattern: "Math & Geometry",
    difficulty: "Easy",
  },
  {
    title: "Powx N",
    link: "https://leetcode.com/problems/powx-n/",
    pattern: "Math & Geometry",
    difficulty: "Medium",
  },
  {
    title: "Multiply Strings",
    link: "https://leetcode.com/problems/multiply-strings/",
    pattern: "Math & Geometry",
    difficulty: "Medium",
  },
  {
    title: "Detect Squares",
    link: "https://leetcode.com/problems/detect-squares/",
    pattern: "Math & Geometry",
    difficulty: "Medium",
  },
  {
    title: "Single Number",
    link: "https://leetcode.com/problems/single-number/",
    pattern: "Bit Manipulation",
    difficulty: "Easy",
  },
  {
    title: "Number Of 1 Bits",
    link: "https://leetcode.com/problems/number-of-1-bits/",
    pattern: "Bit Manipulation",
    difficulty: "Easy",
  },
  {
    title: "Counting Bits",
    link: "https://leetcode.com/problems/counting-bits/",
    pattern: "Bit Manipulation",
    difficulty: "Easy",
  },
  {
    title: "Reverse Bits",
    link: "https://leetcode.com/problems/reverse-bits/",
    pattern: "Bit Manipulation",
    difficulty: "Easy",
  },
  {
    title: "Missing Number",
    link: "https://leetcode.com/problems/missing-number/",
    pattern: "Bit Manipulation",
    difficulty: "Easy",
  },
  {
    title: "Sum Of Two Integers",
    link: "https://leetcode.com/problems/sum-of-two-integers/",
    pattern: "Bit Manipulation",
    difficulty: "Medium",
  },
  {
    title: "Reverse Integer",
    link: "https://leetcode.com/problems/reverse-integer/",
    pattern: "Bit Manipulation",
    difficulty: "Medium",
  },
];
